# Generated by Django 4.0.3 on 2022-03-03 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0004_alter_student_course_alter_student_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=40, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, validators=[django.core.validators.EmailValidator])),
                ('skype_name', models.CharField(blank=True, max_length=40)),
                ('about_me', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('teacher', models.ManyToManyField(to='ielts.teacher')),
            ],
        ),
    ]
