# Generated by Django 4.0.3 on 2022-03-03 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_teacher_groupsession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupsession',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['first_name', 'last_name']},
        ),
    ]
