# Generated by Django 4.0.3 on 2022-03-04 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_groupsession_options_alter_teacher_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsession',
            name='teacher',
            field=models.ManyToManyField(related_name='group_sessions', to='students.teacher'),
        ),
    ]
