# Generated by Django 4.0.3 on 2022-03-21 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0007_alter_groupsession_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupsession',
            name='teacher',
        ),
    ]
