version: "3.9"

services:
  web:
    build: .
    command: ./docker-entrypoint.sh
    ports:
      - 8000:8000
    volumes:
      - IELTSstudents:/app

  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - mysqldata:/var/lib/mysql/

volumes:
  IELTSstudents:
  mysqldata: